*&---------------------------------------------------------------------*
*& Include ZBC405_A16_M04_TOP                       - Report ZBC405_A16_M04
*&---------------------------------------------------------------------*
REPORT zbc405_a16_m04.

DATA gv_chg TYPE c LENGTH 1.

SELECTION-screen BEGIN OF BLOCK bl1 with frame.
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT 3(8) TEXT-t01 FOR FIELD pa_rad1.
  SELECTION-SCREEN POSITION 1.
  PARAMETERS pa_rad1 RADIOBUTTON GROUP rg1 MODIF ID gr1 .
  SELECTION-SCREEN COMMENT pos_low(8) TEXT-t02 FOR FIELD pa_rad2.
  PARAMETERS pa_rad2 RADIOBUTTON GROUP rg1 MODIF ID gr1.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bl1.

TABLES: sflight, sscrfields.

*SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN PUSHBUTTON /pos_low(10) gv_text USER-COMMAND on.

*SUBSCREEN
SELECTION-SCREEN BEGIN OF SCREEN 1100 as SUBSCREEN.
  PARAMETERS pa_car TYPE sflight-carrid.
SELECTION-SCREEN END OF SCREEN 1100.

SELECTION-SCREEN BEGIN OF SCREEN 1200 as SUBSCREEN.
 SELECT-OPTIONS so_fld FOR sflight-fldate.
SELECTION-SCREEN END OF SCREEN 1200.

SELECTION-SCREEN BEGIN OF SCREEN 1300 as SUBSCREEN.
  PARAMETERS pa_con TYPE sflight-connid.
SELECTION-SCREEN END OF SCREEN 1300.

SELECTION-SCREEN BEGIN OF TABBED BLOCK ts_info FOR 5 LINES.
  SELECTION-SCREEN TAB (10) tab1 USER-COMMAND car DEFAULT SCREEN 1100.
  SELECTION-SCREEN TAB (10) tab2 USER-COMMAND fld DEFAULT SCREEN 1200.
  SELECTION-SCREEN TAB (10) tab3 USER-COMMAND con DEFAULT SCREEN 1300.
SELECTION-SCREEN END OF BLOCK ts_info.
