*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVSA16VEN.......................................*
FORM GET_DATA_ZVSA16VEN.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSA16VEN WHERE
(VIM_WHERETAB) .
    CLEAR ZVSA16VEN .
ZVSA16VEN-MANDT =
ZTSA16VEN-MANDT .
ZVSA16VEN-LIFNR =
ZTSA16VEN-LIFNR .
ZVSA16VEN-LAND1 =
ZTSA16VEN-LAND1 .
ZVSA16VEN-NAME1 =
ZTSA16VEN-NAME1 .
ZVSA16VEN-NAME2 =
ZTSA16VEN-NAME2 .
ZVSA16VEN-VENCA =
ZTSA16VEN-VENCA .
ZVSA16VEN-CARRID =
ZTSA16VEN-CARRID .
ZVSA16VEN-MEALNO =
ZTSA16VEN-MEALNO .
ZVSA16VEN-PRICE =
ZTSA16VEN-PRICE .
ZVSA16VEN-WAERS =
ZTSA16VEN-WAERS .
<VIM_TOTAL_STRUC> = ZVSA16VEN.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSA16VEN .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSA16VEN.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSA16VEN-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSA16VEN WHERE
  LIFNR = ZVSA16VEN-LIFNR .
    IF SY-SUBRC = 0.
    DELETE ZTSA16VEN .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSA16VEN WHERE
  LIFNR = ZVSA16VEN-LIFNR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSA16VEN.
    ENDIF.
ZTSA16VEN-MANDT =
ZVSA16VEN-MANDT .
ZTSA16VEN-LIFNR =
ZVSA16VEN-LIFNR .
ZTSA16VEN-LAND1 =
ZVSA16VEN-LAND1 .
ZTSA16VEN-NAME1 =
ZVSA16VEN-NAME1 .
ZTSA16VEN-NAME2 =
ZVSA16VEN-NAME2 .
ZTSA16VEN-VENCA =
ZVSA16VEN-VENCA .
ZTSA16VEN-CARRID =
ZVSA16VEN-CARRID .
ZTSA16VEN-MEALNO =
ZVSA16VEN-MEALNO .
ZTSA16VEN-PRICE =
ZVSA16VEN-PRICE .
ZTSA16VEN-WAERS =
ZVSA16VEN-WAERS .
    IF SY-SUBRC = 0.
    UPDATE ZTSA16VEN ##WARN_OK.
    ELSE.
    INSERT ZTSA16VEN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSA16VEN-UPD_FLAG,
STATUS_ZVSA16VEN-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZVSA16VEN.
  SELECT SINGLE * FROM ZTSA16VEN WHERE
LIFNR = ZVSA16VEN-LIFNR .
ZVSA16VEN-MANDT =
ZTSA16VEN-MANDT .
ZVSA16VEN-LIFNR =
ZTSA16VEN-LIFNR .
ZVSA16VEN-LAND1 =
ZTSA16VEN-LAND1 .
ZVSA16VEN-NAME1 =
ZTSA16VEN-NAME1 .
ZVSA16VEN-NAME2 =
ZTSA16VEN-NAME2 .
ZVSA16VEN-VENCA =
ZTSA16VEN-VENCA .
ZVSA16VEN-CARRID =
ZTSA16VEN-CARRID .
ZVSA16VEN-MEALNO =
ZTSA16VEN-MEALNO .
ZVSA16VEN-PRICE =
ZTSA16VEN-PRICE .
ZVSA16VEN-WAERS =
ZTSA16VEN-WAERS .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSA16VEN USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSA16VEN-LIFNR TO
ZTSA16VEN-LIFNR .
MOVE ZVSA16VEN-MANDT TO
ZTSA16VEN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSA16VEN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSA16VEN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSA16VEN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
