*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVSA16PRO.......................................*
FORM GET_DATA_ZVSA16PRO.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSA16PRO WHERE
(VIM_WHERETAB) .
    CLEAR ZVSA16PRO .
ZVSA16PRO-MANDT =
ZTSA16PRO-MANDT .
ZVSA16PRO-PROID =
ZTSA16PRO-PROID .
ZVSA16PRO-PTYPE =
ZTSA16PRO-PTYPE .
ZVSA16PRO-BUDGET =
ZTSA16PRO-BUDGET .
ZVSA16PRO-WAERS =
ZTSA16PRO-WAERS .
ZVSA16PRO-PERNR =
ZTSA16PRO-PERNR .
    SELECT SINGLE * FROM ZTSA16PRO_T WHERE
PROID = ZTSA16PRO-PROID AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZVSA16PRO-PNAME =
ZTSA16PRO_T-PNAME .
    ENDIF.
<VIM_TOTAL_STRUC> = ZVSA16PRO.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSA16PRO .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSA16PRO.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSA16PRO-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSA16PRO WHERE
  PROID = ZVSA16PRO-PROID .
    IF SY-SUBRC = 0.
    DELETE ZTSA16PRO .
    ENDIF.
    DELETE FROM ZTSA16PRO_T WHERE
    PROID = ZTSA16PRO-PROID .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSA16PRO WHERE
  PROID = ZVSA16PRO-PROID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSA16PRO.
    ENDIF.
ZTSA16PRO-MANDT =
ZVSA16PRO-MANDT .
ZTSA16PRO-PROID =
ZVSA16PRO-PROID .
ZTSA16PRO-PTYPE =
ZVSA16PRO-PTYPE .
ZTSA16PRO-BUDGET =
ZVSA16PRO-BUDGET .
ZTSA16PRO-WAERS =
ZVSA16PRO-WAERS .
ZTSA16PRO-PERNR =
ZVSA16PRO-PERNR .
    IF SY-SUBRC = 0.
    UPDATE ZTSA16PRO ##WARN_OK.
    ELSE.
    INSERT ZTSA16PRO .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZTSA16PRO_T WHERE
    PROID = ZTSA16PRO-PROID AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZTSA16PRO_T.
ZTSA16PRO_T-PROID =
ZTSA16PRO-PROID .
ZTSA16PRO_T-SPRAS =
SY-LANGU .
      ENDIF.
ZTSA16PRO_T-PNAME =
ZVSA16PRO-PNAME .
    IF SY-SUBRC = 0.
    UPDATE ZTSA16PRO_T ##WARN_OK.
    ELSE.
    INSERT ZTSA16PRO_T .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSA16PRO-UPD_FLAG,
STATUS_ZVSA16PRO-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZVSA16PRO.
  SELECT SINGLE * FROM ZTSA16PRO WHERE
PROID = ZVSA16PRO-PROID .
ZVSA16PRO-MANDT =
ZTSA16PRO-MANDT .
ZVSA16PRO-PROID =
ZTSA16PRO-PROID .
ZVSA16PRO-PTYPE =
ZTSA16PRO-PTYPE .
ZVSA16PRO-BUDGET =
ZTSA16PRO-BUDGET .
ZVSA16PRO-WAERS =
ZTSA16PRO-WAERS .
ZVSA16PRO-PERNR =
ZTSA16PRO-PERNR .
    SELECT SINGLE * FROM ZTSA16PRO_T WHERE
PROID = ZTSA16PRO-PROID AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZVSA16PRO-PNAME =
ZTSA16PRO_T-PNAME .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVSA16PRO-PNAME .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSA16PRO USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSA16PRO-PROID TO
ZTSA16PRO-PROID .
MOVE ZVSA16PRO-MANDT TO
ZTSA16PRO-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSA16PRO'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSA16PRO TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSA16PRO'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZTSA16PRO-PROID TO
ZTSA16PRO_T-PROID .
MOVE SY-LANGU TO
ZTSA16PRO_T-SPRAS .
MOVE ZVSA16PRO-MANDT TO
ZTSA16PRO_T-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSA16PRO_T'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSA16PRO_T TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSA16PRO_T'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
