*&---------------------------------------------------------------------*
*& Modulpool SAPBC414_TRAVELAG_T
*&---------------------------------------------------------------------*


INCLUDE ZTRAVELAG_A16_TTOP.
*INCLUDE BC414_TRAVELAG_TTOP.
INCLUDE ZTRAVELAG_A16_TF01.
*INCLUDE BC414_TRAVELAG_TF01.
INCLUDE ZTRAVELAG_A16_TO01.
*INCLUDE BC414_TRAVELAG_TO01.
INCLUDE ZTRAVELAG_A16_TI01.
*INCLUDE BC414_TRAVELAG_TI01.
INCLUDE ZTRAVELAG_A16_TE01.
*INCLUDE BC414_TRAVELAG_TE01.
